### ISSUE TITLE
TIN score calculation uses too many threads

### ISSUE THREAD

**Issue by dominikburri** [zavolanlab/tin-score-calculation#14]
**Describe the bug**
The number of threads, resp. processes, is hardcoded and based on on the CPU count of the PC (see additional context).
This potentially produces lots of scheduling overhead.

During an execution of zarp I noticed that a rule running this script (via singularity image) spawned lots of processes (see screenshot).

**Screenshot**
Taken from a machine with 12 cores, as reported with python's `cpu_count()`.

![bildschirmfoto_2021-05-19_um_11 12 24](https://user-images.githubusercontent.com/7873536/118792910-655c0000-b898-11eb-8e1a-911b06c2cbb7.png)

**Expected behavior**
Define the number of threads as additional parameter.

**Desktop (please complete the following information):**
 - OS: CentOS 7

**Additional context**
The code to adjust: https://github.com/zavolanlab/tin-score-calculation/blob/9d0015571cd1bab9156e7f5f65f00df5c6b43ebe/scripts/calculate-tin.py#L34

**Comment by AngryMaciek** [comment]
This was a purposeful design decision by @mzavolan;
An easy modification would be to introduce a command line flag `--cpu-count` and parse that number from the call.
If this solution is fine with you @dominikburri, please fork this repo, commit change and submit a PR. 

FYI: This is not a bug in the code, `feature request` would be more appropriate than `bug report`.

**Comment by fgypas** [comment]
If you open a new PR please do that in the public [repo](https://github.com/zavolanlab/tin-score-calculation) repo. We should also archive the internal to avoid confusion.

**Comment by AngryMaciek** [comment]
We could add a _default_  value for the parameter and this would be fine, just sth reasonable, not `cpu_count() * 10 `.

**Comment by AngryMaciek** [comment]
Closed with #25
