### ISSUE TITLE
Mac version of tin-score-calculation is slow

### ISSUE THREAD

**Issue by fgypas** [zavolanlab/tin-score-calculation#18]
**Is your feature request related to a problem? Please describe.**
Both the mac version of the CI and a local installation via pip on OS X 10.14.6 seem very slow. Even for the small test files. The same test under Ubuntu runs in 10s while on OSX it takes more than 20 minutes...

**Describe the solution you'd like**
Speed up the process.

**Describe alternatives you've considered**
Or at least understand why this happens.

**Comment by AngryMaciek** [comment]
It is OK to remove `macOS` from the CI for now, then.

**Comment by AngryMaciek** [comment]
Closed with #25
