### ISSUE TITLE
Eliminate dependencies

### ISSUE THREAD

**Issue by fgypas** [zavolanlab/tin-score-calculation#19]
**Is your feature request related to a problem? Please describe.**
I was looking at the dependencies of it seems that we could eliminate some of them. More specifically do we really need the `guppy` package?

https://github.com/zavolanlab/tin-score-calculation/blob/3aeb38415aaa1e726cdbc8731e4c2587ef966d99/scripts/calculate-tin.py#L28

**Describe the solution you'd like**
The maintenance of the package will be easier if we will not use the specific package. 

@mzavolan @meric466 @AngryMaciek Do you think it can be eliminated?

**Comment by AngryMaciek** [comment]
We should remove this; I went through the script and conclude that it is not used anymore in the code:
https://github.com/zavolanlab/tin-score-calculation/blob/3aeb38415aaa1e726cdbc8731e4c2587ef966d99/scripts/calculate-tin.py#L547

**Comment by fgypas** [comment]
Great. This means that we don't have to care for guppy in the future. I spent a lot of time making `guppy3` available in `conda-forge`: https://github.com/conda-forge/staged-recipes/pull/14913 and I am afraid that it will cause issues in the future.

Can someone from you work on it?

Note that this might also fix #18

**Comment by fgypas** [comment]
Also, forgot to mention. We don't have to do that for this release, but it would be good to fix it before we publish zarp.
