### ISSUE TITLE
Update documentation for version 0.5

### ISSUE THREAD

**Issue by fgypas** [zavolanlab/tin-score-calculation#21]
**Is your feature request related to a problem? Please describe.**
Update documentation for version 0.5

**Describe the solution you'd like**
Add conda and docker correct info:
- docker://quay.io/biocontainers/tin-score-calculation:0.5--pyh5e36f6f_0
- https://anaconda.org/bioconda/tin-score-calculation/labels (version 0.5)

**Comment by fgypas** [comment]
This could be combined with the addition of a few new badges:
https://anaconda.org/bioconda/tin-score-calculation/badges

**Comment by AngryMaciek** [comment]
It would be better to leave version `0.5.0` as was; that is why I bumped-up patch version to `0.5.1` in #20.

**Comment by fgypas** [comment]
So, let's update this once 0.5.1 is ready.

**Comment by AngryMaciek** [comment]
@fgypas : _publish_ Action finished in the CI for `0.5.1`.
