### ISSUE TITLE
clean docker-related files

### ISSUE THREAD

**Issue by AngryMaciek** [zavolanlab/tin-score-calculation#3]
**Is your feature request related to a problem? Please describe.**
There are several Dockerfiles laying around in the repository, It's best to decide on the main one and set how do we proceed with deploying the container.

**Comment by AngryMaciek** [comment]
Respective section in the README.md will have to be adjusted too.

**Comment by AngryMaciek** [comment]
@fgypas @uniqueg 
We will later have to decide on the strategy here.

**Comment by fgypas** [comment]
For this, I would just use the docker image from biocontainers that will be generated after #12 and some extra steps.
