### ISSUE TITLE
BED file / possible to use GTF directly?

### ISSUE THREAD

**Issue by grexor** [zavolanlab/tin-score-calculation#30]
Great work, two questions:

* is there a tool to make the correct BED file for tin-score-calculation from a GTF, or do you have BED files downloadable for human and mouse somewhere (possibly with latest assemblies and annotations from Ensembl?)
* easiest would be: is it possible to use a GTF directly?

Thanks,
Gregor

**Comment by uniqueg** [comment]
Thanks for your question and suggestion, Gregor! Great idea

@mzavolan @mkatsanto: What do you think?

**Comment by mkatsanto** [comment]
Thanks for the question. We do this in https://github.com/zavolanlab/zarp/tree/dev 

One of the steps converts the gtf to bed using gtf2bed12 from the zgtf package (https://github.com/zavolanlab/zgtf), see here:
https://github.com/zavolanlab/zarp/blob/ac953471b475b9f1b81ac08679d01fc4c2f98d9d/workflow/Snakefile#L683

**Comment by grexor** [comment]
Thanks everyone, will check it out 👍
